# PostgreSQL. Versions 9.1 and up are supported.
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  host: localhost
  username: pguser
  password: pguser_password
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: written_by_women_development

test:
  <<: *default
  database: written_by_women_test

production:
  <<: *default
  database: written_by_women_production
